INSERT INTO locations SET id=32, woj_id=null, name="Zachodniopomorskie";
INSERT INTO locations SET id=2, woj_id=null, name="Dolnośląskie";
INSERT INTO locations SET id=4, woj_id=null, name="Kujawsko-pomorskie";
INSERT INTO locations SET id=6, woj_id=null, name="Lubelskie";
INSERT INTO locations SET id=8, woj_id=null, name="Lubuskie";
INSERT INTO locations SET id=10, woj_id=null, name="Łódzkie";
INSERT INTO locations SET id=12, woj_id=null, name="Małopolskie";
INSERT INTO locations SET id=14, woj_id=null, name="Mazowieckie";
INSERT INTO locations SET id=16, woj_id=null, name="Opolskie";
INSERT INTO locations SET id=18, woj_id=null, name="Podkarpackie";
INSERT INTO locations SET id=20, woj_id=null, name="Podlaskie";
INSERT INTO locations SET id=22, woj_id=null, name="Pomorskie";
INSERT INTO locations SET id=24, woj_id=null, name="Śląskie";
INSERT INTO locations SET id=26, woj_id=null, name="Świętokrzyskie";
INSERT INTO locations SET id=28, woj_id=null, name="Warmińsko-mazurskie";
INSERT INTO locations SET id=30, woj_id=null, name="Wielkopolskie";
INSERT INTO locations SET woj_id=32, name="Karlino";
INSERT INTO locations SET woj_id=32, name="Tychowo";
INSERT INTO locations SET woj_id=32, name="Choszczno";
INSERT INTO locations SET woj_id=32, name="Drawno";
INSERT INTO locations SET woj_id=32, name="Pełczyce";
INSERT INTO locations SET woj_id=32, name="Recz";
INSERT INTO locations SET woj_id=32, name="Czaplinek";
INSERT INTO locations SET woj_id=32, name="Drawsko Pomorskie";
INSERT INTO locations SET woj_id=32, name="Kalisz Pomorski";
INSERT INTO locations SET woj_id=32, name="Złocieniec";
INSERT INTO locations SET woj_id=32, name="Goleniów";
INSERT INTO locations SET woj_id=32, name="Maszewo";
INSERT INTO locations SET woj_id=32, name="Nowogard";
INSERT INTO locations SET woj_id=32, name="Gryfice";
INSERT INTO locations SET woj_id=32, name="Płoty";
INSERT INTO locations SET woj_id=32, name="Trzebiatów";
INSERT INTO locations SET woj_id=32, name="Cedynia";
INSERT INTO locations SET woj_id=32, name="Chojna";
INSERT INTO locations SET woj_id=32, name="Gryfino";
INSERT INTO locations SET woj_id=32, name="Mieszkowice";
INSERT INTO locations SET woj_id=32, name="Moryń";
INSERT INTO locations SET woj_id=32, name="Trzcińsko-Zdrój";
INSERT INTO locations SET woj_id=32, name="Dziwnów";
INSERT INTO locations SET woj_id=32, name="Golczewo";
INSERT INTO locations SET woj_id=32, name="Kamień Pomorski";
INSERT INTO locations SET woj_id=32, name="Międzyzdroje";
INSERT INTO locations SET woj_id=32, name="Wolin";
INSERT INTO locations SET woj_id=32, name="Gościno";
INSERT INTO locations SET woj_id=32, name="Bobolice";
INSERT INTO locations SET woj_id=32, name="Polanów";
INSERT INTO locations SET woj_id=32, name="Sianów";
INSERT INTO locations SET woj_id=32, name="Barlinek";
INSERT INTO locations SET woj_id=32, name="Dębno";
INSERT INTO locations SET woj_id=32, name="Myślibórz";
INSERT INTO locations SET woj_id=32, name="Nowe Warpno";
INSERT INTO locations SET woj_id=32, name="Police";
INSERT INTO locations SET woj_id=32, name="Lipiany";
INSERT INTO locations SET woj_id=32, name="Pyrzyce";
INSERT INTO locations SET woj_id=32, name="Chociwel";
INSERT INTO locations SET woj_id=32, name="Dobrzany";
INSERT INTO locations SET woj_id=32, name="Ińsko";
INSERT INTO locations SET woj_id=32, name="Suchań";
INSERT INTO locations SET woj_id=32, name="Barwice";
INSERT INTO locations SET woj_id=32, name="Biały Bór";
INSERT INTO locations SET woj_id=32, name="Borne Sulinowo";
INSERT INTO locations SET woj_id=32, name="Połczyn-Zdrój";
INSERT INTO locations SET woj_id=32, name="Człopa";
INSERT INTO locations SET woj_id=32, name="Mirosławiec";
INSERT INTO locations SET woj_id=32, name="Tuczno";
INSERT INTO locations SET woj_id=32, name="Dobra";
INSERT INTO locations SET woj_id=32, name="Łobez";
INSERT INTO locations SET woj_id=32, name="Resko";
INSERT INTO locations SET woj_id=32, name="Węgorzyno";
INSERT INTO locations SET woj_id=32, name="Koszalin";
INSERT INTO locations SET woj_id=32, name="Szczecin";
INSERT INTO locations SET woj_id=32, name="Świnoujście";
INSERT INTO locations SET woj_id=2, name="Nowogrodziec";
INSERT INTO locations SET woj_id=2, name="Niemcza";
INSERT INTO locations SET woj_id=2, name="Góra";
INSERT INTO locations SET woj_id=2, name="Wąsosz";
INSERT INTO locations SET woj_id=2, name="Bolków";
INSERT INTO locations SET woj_id=2, name="Lubawka";
INSERT INTO locations SET woj_id=2, name="Bystrzyca Kłodzka";
INSERT INTO locations SET woj_id=2, name="Lądek-Zdrój";
INSERT INTO locations SET woj_id=2, name="Międzylesie";
INSERT INTO locations SET woj_id=2, name="Radków";
INSERT INTO locations SET woj_id=2, name="Stronie Śląskie";
INSERT INTO locations SET woj_id=2, name="Szczytna";
INSERT INTO locations SET woj_id=2, name="Prochowice";
INSERT INTO locations SET woj_id=2, name="Leśna";
INSERT INTO locations SET woj_id=2, name="Olszyna";
INSERT INTO locations SET woj_id=2, name="Ścinawa";
INSERT INTO locations SET woj_id=2, name="Gryfów Śląski";
INSERT INTO locations SET woj_id=2, name="Lubomierz";
INSERT INTO locations SET woj_id=2, name="Lwówek Śląski";
INSERT INTO locations SET woj_id=2, name="Mirsk";
INSERT INTO locations SET woj_id=2, name="Wleń";
INSERT INTO locations SET woj_id=2, name="Milicz";
INSERT INTO locations SET woj_id=2, name="Bierutów";
INSERT INTO locations SET woj_id=2, name="Międzybórz";
INSERT INTO locations SET woj_id=2, name="Syców";
INSERT INTO locations SET woj_id=2, name="Twardogóra";
INSERT INTO locations SET woj_id=2, name="Jelcz-Laskowice";
INSERT INTO locations SET woj_id=2, name="Chocianów";
INSERT INTO locations SET woj_id=2, name="Polkowice";
INSERT INTO locations SET woj_id=2, name="Przemków";
INSERT INTO locations SET woj_id=2, name="Strzelin";
INSERT INTO locations SET woj_id=2, name="Wiązów";
INSERT INTO locations SET woj_id=2, name="Środa Śląska";
INSERT INTO locations SET woj_id=2, name="Jaworzyna Śląska";
INSERT INTO locations SET woj_id=2, name="Strzegom";
INSERT INTO locations SET woj_id=2, name="Żarów";
INSERT INTO locations SET woj_id=2, name="Oborniki Śląskie";
INSERT INTO locations SET woj_id=2, name="Prusice";
INSERT INTO locations SET woj_id=2, name="Trzebnica";
INSERT INTO locations SET woj_id=2, name="Żmigród";
INSERT INTO locations SET woj_id=2, name="Głuszyca";
INSERT INTO locations SET woj_id=2, name="Mieroszów";
INSERT INTO locations SET woj_id=2, name="Brzeg Dolny";
INSERT INTO locations SET woj_id=2, name="Wołów";
INSERT INTO locations SET woj_id=2, name="Kąty Wrocławskie";
INSERT INTO locations SET woj_id=2, name="Sobótka";
INSERT INTO locations SET woj_id=2, name="Siechnice";
INSERT INTO locations SET woj_id=2, name="Bardo";
INSERT INTO locations SET woj_id=2, name="Ząbkowice Śląskie";
INSERT INTO locations SET woj_id=2, name="Ziębice";
INSERT INTO locations SET woj_id=2, name="Złoty Stok";
INSERT INTO locations SET woj_id=2, name="Bogatynia";
INSERT INTO locations SET woj_id=2, name="Pieńsk";
INSERT INTO locations SET woj_id=2, name="Węgliniec";
INSERT INTO locations SET woj_id=2, name="Świerzawa";
INSERT INTO locations SET woj_id=2, name="Jelenia Góra";
INSERT INTO locations SET woj_id=2, name="Legnica";
INSERT INTO locations SET woj_id=2, name="Wrocław";
INSERT INTO locations SET woj_id=2, name="Wałbrzych";
INSERT INTO locations SET woj_id=4, name="Górzno";
INSERT INTO locations SET woj_id=4, name="Jabłonowo Pomorskie";
INSERT INTO locations SET woj_id=4, name="Koronowo";
INSERT INTO locations SET woj_id=4, name="Solec Kujawski";
INSERT INTO locations SET woj_id=4, name="Kowalewo Pomorskie";
INSERT INTO locations SET woj_id=4, name="Łasin";
INSERT INTO locations SET woj_id=4, name="Radzyń Chełmiński";
INSERT INTO locations SET woj_id=4, name="Gniewkowo";
INSERT INTO locations SET woj_id=4, name="Janikowo";
INSERT INTO locations SET woj_id=4, name="Kruszwica";
INSERT INTO locations SET woj_id=4, name="Pakość";
INSERT INTO locations SET woj_id=4, name="Dobrzyń nad Wisłą";
INSERT INTO locations SET woj_id=4, name="Skępe";
INSERT INTO locations SET woj_id=4, name="Mogilno";
INSERT INTO locations SET woj_id=4, name="Strzelno";
INSERT INTO locations SET woj_id=4, name="Kcynia";
INSERT INTO locations SET woj_id=4, name="Mrocza";
INSERT INTO locations SET woj_id=4, name="Nakło nad Notecią";
INSERT INTO locations SET woj_id=4, name="Szubin";
INSERT INTO locations SET woj_id=4, name="Piotrków Kujawski";
INSERT INTO locations SET woj_id=4, name="Kamień Krajeński";
INSERT INTO locations SET woj_id=4, name="Sępólno Krajeńskie";
INSERT INTO locations SET woj_id=4, name="Więcbork";
INSERT INTO locations SET woj_id=4, name="Nowe";
INSERT INTO locations SET woj_id=4, name="Świecie";
INSERT INTO locations SET woj_id=4, name="Tuchola";
INSERT INTO locations SET woj_id=4, name="Brześć Kujawski";
INSERT INTO locations SET woj_id=4, name="Chodecz";
INSERT INTO locations SET woj_id=4, name="Izbica Kujawska";
INSERT INTO locations SET woj_id=4, name="Lubień Kujawski";
INSERT INTO locations SET woj_id=4, name="Lubraniec";
INSERT INTO locations SET woj_id=4, name="Barcin";
INSERT INTO locations SET woj_id=4, name="Janowiec Wielkopolski";
INSERT INTO locations SET woj_id=4, name="Łabiszyn";
INSERT INTO locations SET woj_id=4, name="Żnin";
INSERT INTO locations SET woj_id=4, name="Bydgoszcz";
INSERT INTO locations SET woj_id=4, name="Grudziądz";
INSERT INTO locations SET woj_id=4, name="Toruń";
INSERT INTO locations SET woj_id=4, name="Włocławek";
INSERT INTO locations SET woj_id=6, name="Frampol";
INSERT INTO locations SET woj_id=6, name="Józefów";
INSERT INTO locations SET woj_id=6, name="Tarnogród";
INSERT INTO locations SET woj_id=6, name="Janów Lubelski";
INSERT INTO locations SET woj_id=6, name="Annopol";
INSERT INTO locations SET woj_id=6, name="Kock";
INSERT INTO locations SET woj_id=6, name="Ostrów Lubelski";
INSERT INTO locations SET woj_id=6, name="Bełżyce";
INSERT INTO locations SET woj_id=6, name="Bychawa";
INSERT INTO locations SET woj_id=6, name="Łęczna";
INSERT INTO locations SET woj_id=6, name="Opole Lubelskie";
INSERT INTO locations SET woj_id=6, name="Poniatowa";
INSERT INTO locations SET woj_id=6, name="Parczew";
INSERT INTO locations SET woj_id=6, name="Kazimierz Dolny";
INSERT INTO locations SET woj_id=6, name="Nałęczów";
INSERT INTO locations SET woj_id=6, name="Ryki";
INSERT INTO locations SET woj_id=6, name="Piaski";
INSERT INTO locations SET woj_id=6, name="Łaszczów";
INSERT INTO locations SET woj_id=6, name="Tyszowce";
INSERT INTO locations SET woj_id=6, name="Krasnobród";
INSERT INTO locations SET woj_id=6, name="Szczebrzeszyn";
INSERT INTO locations SET woj_id=6, name="Zwierzyniec";
INSERT INTO locations SET woj_id=6, name="Biała Podlaska";
INSERT INTO locations SET woj_id=6, name="Chełm";
INSERT INTO locations SET woj_id=6, name="Lublin";
INSERT INTO locations SET woj_id=6, name="Zamość";
INSERT INTO locations SET woj_id=8, name="Witnica";
INSERT INTO locations SET woj_id=8, name="Krosno Odrzańskie";
INSERT INTO locations SET woj_id=8, name="Międzyrzecz";
INSERT INTO locations SET woj_id=8, name="Skwierzyna";
INSERT INTO locations SET woj_id=8, name="Trzciel";
INSERT INTO locations SET woj_id=8, name="Bytom Odrzański";
INSERT INTO locations SET woj_id=8, name="Kożuchów";
INSERT INTO locations SET woj_id=8, name="Nowe Miasteczko";
INSERT INTO locations SET woj_id=8, name="Cybinka";
INSERT INTO locations SET woj_id=8, name="Ośno Lubuskie";
INSERT INTO locations SET woj_id=8, name="Rzepin";
INSERT INTO locations SET woj_id=8, name="Słubice";
INSERT INTO locations SET woj_id=8, name="Dobiegniew";
INSERT INTO locations SET woj_id=8, name="Drezdenko";
INSERT INTO locations SET woj_id=8, name="Strzelce Krajeńskie";
INSERT INTO locations SET woj_id=8, name="Lubniewice";
INSERT INTO locations SET woj_id=8, name="Sulęcin";
INSERT INTO locations SET woj_id=8, name="Torzym";
INSERT INTO locations SET woj_id=8, name="Świebodzin";
INSERT INTO locations SET woj_id=8, name="Zbąszynek";
INSERT INTO locations SET woj_id=8, name="Babimost";
INSERT INTO locations SET woj_id=8, name="Czerwieńsk";
INSERT INTO locations SET woj_id=8, name="Kargowa";
INSERT INTO locations SET woj_id=8, name="Nowogród Bobrzański";
INSERT INTO locations SET woj_id=8, name="Sulechów";
INSERT INTO locations SET woj_id=8, name="Iłowa";
INSERT INTO locations SET woj_id=8, name="Małomice";
INSERT INTO locations SET woj_id=8, name="Szprotawa";
INSERT INTO locations SET woj_id=8, name="Jasień";
INSERT INTO locations SET woj_id=8, name="Lubsko";
INSERT INTO locations SET woj_id=8, name="Sława";
INSERT INTO locations SET woj_id=8, name="Szlichtyngowa";
INSERT INTO locations SET woj_id=8, name="Wschowa";
INSERT INTO locations SET woj_id=8, name="Gorzów Wielkopolski";
INSERT INTO locations SET woj_id=8, name="Zielona Góra";
INSERT INTO locations SET woj_id=10, name="Zelów";
INSERT INTO locations SET woj_id=10, name="Krośniewice";
INSERT INTO locations SET woj_id=10, name="Żychlin";
INSERT INTO locations SET woj_id=10, name="Łask";
INSERT INTO locations SET woj_id=10, name="Koluszki";
INSERT INTO locations SET woj_id=10, name="Rzgów";
INSERT INTO locations SET woj_id=10, name="Tuszyn";
INSERT INTO locations SET woj_id=10, name="Drzewica";
INSERT INTO locations SET woj_id=10, name="Opoczno";
INSERT INTO locations SET woj_id=10, name="Działoszyn";
INSERT INTO locations SET woj_id=10, name="Pajęczno";
INSERT INTO locations SET woj_id=10, name="Sulejów";
INSERT INTO locations SET woj_id=10, name="Wolbórz";
INSERT INTO locations SET woj_id=10, name="Poddębice";
INSERT INTO locations SET woj_id=10, name="Uniejów";
INSERT INTO locations SET woj_id=10, name="Kamieńsk";
INSERT INTO locations SET woj_id=10, name="Przedbórz";
INSERT INTO locations SET woj_id=10, name="Biała Rawska";
INSERT INTO locations SET woj_id=10, name="Błaszki";
INSERT INTO locations SET woj_id=10, name="Warta";
INSERT INTO locations SET woj_id=10, name="Złoczew";
INSERT INTO locations SET woj_id=10, name="Wieluń";
INSERT INTO locations SET woj_id=10, name="Wieruszów";
INSERT INTO locations SET woj_id=10, name="Szadek";
INSERT INTO locations SET woj_id=10, name="Aleksandrów Łódzki";
INSERT INTO locations SET woj_id=10, name="Stryków";
INSERT INTO locations SET woj_id=10, name="Łódź";
INSERT INTO locations SET woj_id=10, name="Piotrków Trybunalski";
INSERT INTO locations SET woj_id=10, name="Skierniewice";
INSERT INTO locations SET woj_id=12, name="Nowy Wiśnicz";
INSERT INTO locations SET woj_id=12, name="Brzesko";
INSERT INTO locations SET woj_id=12, name="Czchów";
INSERT INTO locations SET woj_id=12, name="Alwernia";
INSERT INTO locations SET woj_id=12, name="Chrzanów";
INSERT INTO locations SET woj_id=12, name="Libiąż";
INSERT INTO locations SET woj_id=12, name="Trzebinia";
INSERT INTO locations SET woj_id=12, name="Dąbrowa Tarnowska";
INSERT INTO locations SET woj_id=12, name="Szczucin";
INSERT INTO locations SET woj_id=12, name="Biecz";
INSERT INTO locations SET woj_id=12, name="Bobowa";
INSERT INTO locations SET woj_id=12, name="Krzeszowice";
INSERT INTO locations SET woj_id=12, name="Skała";
INSERT INTO locations SET woj_id=12, name="Skawina";
INSERT INTO locations SET woj_id=12, name="Słomniki";
INSERT INTO locations SET woj_id=12, name="Świątniki Górne";
INSERT INTO locations SET woj_id=12, name="Miechów";
INSERT INTO locations SET woj_id=12, name="Dobczyce";
INSERT INTO locations SET woj_id=12, name="Myślenice";
INSERT INTO locations SET woj_id=12, name="Sułkowice";
INSERT INTO locations SET woj_id=12, name="Krynica-Zdrój";
INSERT INTO locations SET woj_id=12, name="Muszyna";
INSERT INTO locations SET woj_id=12, name="Piwniczna-Zdrój";
INSERT INTO locations SET woj_id=12, name="Stary Sącz";
INSERT INTO locations SET woj_id=12, name="Szczawnica";
INSERT INTO locations SET woj_id=12, name="Rabka-Zdrój";
INSERT INTO locations SET woj_id=12, name="Olkusz";
INSERT INTO locations SET woj_id=12, name="Wolbrom";
INSERT INTO locations SET woj_id=12, name="Brzeszcze";
INSERT INTO locations SET woj_id=12, name="Chełmek";
INSERT INTO locations SET woj_id=12, name="Kęty";
INSERT INTO locations SET woj_id=12, name="Zator";
INSERT INTO locations SET woj_id=12, name="Nowe Brzesko";
INSERT INTO locations SET woj_id=12, name="Proszowice";
INSERT INTO locations SET woj_id=12, name="Maków Podhalański";
INSERT INTO locations SET woj_id=12, name="Ciężkowice";
INSERT INTO locations SET woj_id=12, name="Radłów";
INSERT INTO locations SET woj_id=12, name="Ryglice";
INSERT INTO locations SET woj_id=12, name="Tuchów";
INSERT INTO locations SET woj_id=12, name="Wojnicz";
INSERT INTO locations SET woj_id=12, name="Zakliczyn";
INSERT INTO locations SET woj_id=12, name="Żabno";
INSERT INTO locations SET woj_id=12, name="Andrychów";
INSERT INTO locations SET woj_id=12, name="Kalwaria Zebrzydowska";
INSERT INTO locations SET woj_id=12, name="Wadowice";
INSERT INTO locations SET woj_id=12, name="Niepołomice";
INSERT INTO locations SET woj_id=12, name="Wieliczka";
INSERT INTO locations SET woj_id=12, name="Kraków";
INSERT INTO locations SET woj_id=12, name="Nowy Sącz";
INSERT INTO locations SET woj_id=12, name="Tarnów";
INSERT INTO locations SET woj_id=14, name="Białobrzegi";
INSERT INTO locations SET woj_id=14, name="Wyśmierzyce";
INSERT INTO locations SET woj_id=14, name="Glinojeck";
INSERT INTO locations SET woj_id=14, name="Pilawa";
INSERT INTO locations SET woj_id=14, name="Żelechów";
INSERT INTO locations SET woj_id=14, name="Grodzisk Mazowiecki";
INSERT INTO locations SET woj_id=14, name="Grójec";
INSERT INTO locations SET woj_id=14, name="Mogielnica";
INSERT INTO locations SET woj_id=14, name="Nowe Miasto nad Pilicą";
INSERT INTO locations SET woj_id=14, name="Warka";
INSERT INTO locations SET woj_id=14, name="Kozienice";
INSERT INTO locations SET woj_id=14, name="Serock";
INSERT INTO locations SET woj_id=14, name="Lipsko";
INSERT INTO locations SET woj_id=14, name="Łosice";
INSERT INTO locations SET woj_id=14, name="Różan";
INSERT INTO locations SET woj_id=14, name="Halinów";
INSERT INTO locations SET woj_id=14, name="Kałuszyn";
INSERT INTO locations SET woj_id=14, name="Nasielsk";
INSERT INTO locations SET woj_id=14, name="Zakroczym";
INSERT INTO locations SET woj_id=14, name="Myszyniec";
INSERT INTO locations SET woj_id=14, name="Brok";
INSERT INTO locations SET woj_id=14, name="Karczew";
INSERT INTO locations SET woj_id=14, name="Góra Kalwaria";
INSERT INTO locations SET woj_id=14, name="Konstancin-Jeziorna";
INSERT INTO locations SET woj_id=14, name="Piaseczno";
INSERT INTO locations SET woj_id=14, name="Tarczyn";
INSERT INTO locations SET woj_id=14, name="Drobin";
INSERT INTO locations SET woj_id=14, name="Gąbin";
INSERT INTO locations SET woj_id=14, name="Wyszogród";
INSERT INTO locations SET woj_id=14, name="Brwinów";
INSERT INTO locations SET woj_id=14, name="Chorzele";
INSERT INTO locations SET woj_id=14, name="Przysucha";
INSERT INTO locations SET woj_id=14, name="Pułtusk";
INSERT INTO locations SET woj_id=14, name="Iłża";
INSERT INTO locations SET woj_id=14, name="Skaryszew";
INSERT INTO locations SET woj_id=14, name="Mordy";
INSERT INTO locations SET woj_id=14, name="Kosów Lacki";
INSERT INTO locations SET woj_id=14, name="Szydłowiec";
INSERT INTO locations SET woj_id=14, name="Błonie";
INSERT INTO locations SET woj_id=14, name="Łomianki";
INSERT INTO locations SET woj_id=14, name="Ożarów Mazowiecki";
INSERT INTO locations SET woj_id=14, name="Łochów";
INSERT INTO locations SET woj_id=14, name="Radzymin";
INSERT INTO locations SET woj_id=14, name="Tłuszcz";
INSERT INTO locations SET woj_id=14, name="Wołomin";
INSERT INTO locations SET woj_id=14, name="Wyszków";
INSERT INTO locations SET woj_id=14, name="Zwoleń";
INSERT INTO locations SET woj_id=14, name="Bieżuń";
INSERT INTO locations SET woj_id=14, name="Żuromin";
INSERT INTO locations SET woj_id=14, name="Mszczonów";
INSERT INTO locations SET woj_id=14, name="Ostrołęka";
INSERT INTO locations SET woj_id=14, name="Płock";
INSERT INTO locations SET woj_id=14, name="Radom";
INSERT INTO locations SET woj_id=14, name="Siedlce";
INSERT INTO locations SET woj_id=14, name="Warszawa";
INSERT INTO locations SET woj_id=16, name="Grodków";
INSERT INTO locations SET woj_id=16, name="Lewin Brzeski";
INSERT INTO locations SET woj_id=16, name="Baborów";
INSERT INTO locations SET woj_id=16, name="Głubczyce";
INSERT INTO locations SET woj_id=16, name="Kietrz";
INSERT INTO locations SET woj_id=16, name="Byczyna";
INSERT INTO locations SET woj_id=16, name="Kluczbork";
INSERT INTO locations SET woj_id=16, name="Wołczyn";
INSERT INTO locations SET woj_id=16, name="Gogolin";
INSERT INTO locations SET woj_id=16, name="Krapkowice";
INSERT INTO locations SET woj_id=16, name="Zdzieszowice";
INSERT INTO locations SET woj_id=16, name="Namysłów";
INSERT INTO locations SET woj_id=16, name="Głuchołazy";
INSERT INTO locations SET woj_id=16, name="Korfantów";
INSERT INTO locations SET woj_id=16, name="Nysa";
INSERT INTO locations SET woj_id=16, name="Otmuchów";
INSERT INTO locations SET woj_id=16, name="Paczków";
INSERT INTO locations SET woj_id=16, name="Dobrodzień";
INSERT INTO locations SET woj_id=16, name="Gorzów Śląski";
INSERT INTO locations SET woj_id=16, name="Olesno";
INSERT INTO locations SET woj_id=16, name="Praszka";
INSERT INTO locations SET woj_id=16, name="Niemodlin";
INSERT INTO locations SET woj_id=16, name="Ozimek";
INSERT INTO locations SET woj_id=16, name="Prószków";
INSERT INTO locations SET woj_id=16, name="Biała";
INSERT INTO locations SET woj_id=16, name="Głogówek";
INSERT INTO locations SET woj_id=16, name="Prudnik";
INSERT INTO locations SET woj_id=16, name="Kolonowskie";
INSERT INTO locations SET woj_id=16, name="Leśnica";
INSERT INTO locations SET woj_id=16, name="Strzelce Opolskie";
INSERT INTO locations SET woj_id=16, name="Ujazd";
INSERT INTO locations SET woj_id=16, name="Zawadzkie";
INSERT INTO locations SET woj_id=16, name="Opole";
INSERT INTO locations SET woj_id=18, name="Ustrzyki Dolne";
INSERT INTO locations SET woj_id=18, name="Brzozów";
INSERT INTO locations SET woj_id=18, name="Brzostek";
INSERT INTO locations SET woj_id=18, name="Pilzno";
INSERT INTO locations SET woj_id=18, name="Pruchnik";
INSERT INTO locations SET woj_id=18, name="Kołaczyce";
INSERT INTO locations SET woj_id=18, name="Kolbuszowa";
INSERT INTO locations SET woj_id=18, name="Dukla";
INSERT INTO locations SET woj_id=18, name="Iwonicz-Zdrój";
INSERT INTO locations SET woj_id=18, name="Jedlicze";
INSERT INTO locations SET woj_id=18, name="Rymanów";
INSERT INTO locations SET woj_id=18, name="Nowa Sarzyna";
INSERT INTO locations SET woj_id=18, name="Cieszanów";
INSERT INTO locations SET woj_id=18, name="Narol";
INSERT INTO locations SET woj_id=18, name="Oleszyce";
INSERT INTO locations SET woj_id=18, name="Przecław";
INSERT INTO locations SET woj_id=18, name="Radomyśl Wielki";
INSERT INTO locations SET woj_id=18, name="Nisko";
INSERT INTO locations SET woj_id=18, name="Rudnik nad Sanem";
INSERT INTO locations SET woj_id=18, name="Ulanów";
INSERT INTO locations SET woj_id=18, name="Kańczuga";
INSERT INTO locations SET woj_id=18, name="Sieniawa";
INSERT INTO locations SET woj_id=18, name="Ropczyce";
INSERT INTO locations SET woj_id=18, name="Sędziszów Małopolski";
INSERT INTO locations SET woj_id=18, name="Błażowa";
INSERT INTO locations SET woj_id=18, name="Boguchwała";
INSERT INTO locations SET woj_id=18, name="Głogów Małopolski";
INSERT INTO locations SET woj_id=18, name="Sokołów Małopolski";
INSERT INTO locations SET woj_id=18, name="Tyczyn";
INSERT INTO locations SET woj_id=18, name="Zagórz";
INSERT INTO locations SET woj_id=18, name="Strzyżów";
INSERT INTO locations SET woj_id=18, name="Baranów Sandomierski";
INSERT INTO locations SET woj_id=18, name="Nowa Dęba";
INSERT INTO locations SET woj_id=18, name="Lesko";
INSERT INTO locations SET woj_id=18, name="Krosno";
INSERT INTO locations SET woj_id=18, name="Przemyśl";
INSERT INTO locations SET woj_id=18, name="Rzeszów";
INSERT INTO locations SET woj_id=18, name="Tarnobrzeg";
INSERT INTO locations SET woj_id=20, name="Lipsk";
INSERT INTO locations SET woj_id=20, name="Choroszcz";
INSERT INTO locations SET woj_id=20, name="Czarna Białostocka";
INSERT INTO locations SET woj_id=20, name="Łapy";
INSERT INTO locations SET woj_id=20, name="Michałowo";
INSERT INTO locations SET woj_id=20, name="Supraśl";
INSERT INTO locations SET woj_id=20, name="Suraż";
INSERT INTO locations SET woj_id=20, name="Tykocin";
INSERT INTO locations SET woj_id=20, name="Wasilków";
INSERT INTO locations SET woj_id=20, name="Zabłudów";
INSERT INTO locations SET woj_id=20, name="Rajgród";
INSERT INTO locations SET woj_id=20, name="Szczuczyn";
INSERT INTO locations SET woj_id=20, name="Kleszczele";
INSERT INTO locations SET woj_id=20, name="Stawiski";
INSERT INTO locations SET woj_id=20, name="Jedwabne";
INSERT INTO locations SET woj_id=20, name="Nowogród";
INSERT INTO locations SET woj_id=20, name="Goniądz";
INSERT INTO locations SET woj_id=20, name="Knyszyn";
INSERT INTO locations SET woj_id=20, name="Mońki";
INSERT INTO locations SET woj_id=20, name="Drohiczyn";
INSERT INTO locations SET woj_id=20, name="Dąbrowa Białostocka";
INSERT INTO locations SET woj_id=20, name="Krynki";
INSERT INTO locations SET woj_id=20, name="Sokółka";
INSERT INTO locations SET woj_id=20, name="Suchowola";
INSERT INTO locations SET woj_id=20, name="Ciechanowiec";
INSERT INTO locations SET woj_id=20, name="Czyżew";
INSERT INTO locations SET woj_id=20, name="Szepietowo";
INSERT INTO locations SET woj_id=20, name="Białystok";
INSERT INTO locations SET woj_id=20, name="Łomża";
INSERT INTO locations SET woj_id=20, name="Suwałki";
INSERT INTO locations SET woj_id=22, name="Bytów";
INSERT INTO locations SET woj_id=22, name="Miastko";
INSERT INTO locations SET woj_id=22, name="Brusy";
INSERT INTO locations SET woj_id=22, name="Czersk";
INSERT INTO locations SET woj_id=22, name="Czarne";
INSERT INTO locations SET woj_id=22, name="Debrzno";
INSERT INTO locations SET woj_id=22, name="Kartuzy";
INSERT INTO locations SET woj_id=22, name="Żukowo";
INSERT INTO locations SET woj_id=22, name="Prabuty";
INSERT INTO locations SET woj_id=22, name="Nowy Staw";
INSERT INTO locations SET woj_id=22, name="Nowy Dwór Gdański";
INSERT INTO locations SET woj_id=22, name="Kępice";
INSERT INTO locations SET woj_id=22, name="Skarszewy";
INSERT INTO locations SET woj_id=22, name="Gniew";
INSERT INTO locations SET woj_id=22, name="Pelplin";
INSERT INTO locations SET woj_id=22, name="Dzierzgoń";
INSERT INTO locations SET woj_id=22, name="Sztum";
INSERT INTO locations SET woj_id=22, name="Gdańsk";
INSERT INTO locations SET woj_id=22, name="Gdynia";
INSERT INTO locations SET woj_id=22, name="Słupsk";
INSERT INTO locations SET woj_id=22, name="Sopot";
INSERT INTO locations SET woj_id=24, name="Siewierz";
INSERT INTO locations SET woj_id=24, name="Czechowice-Dziedzice";
INSERT INTO locations SET woj_id=24, name="Wilamowice";
INSERT INTO locations SET woj_id=24, name="Skoczów";
INSERT INTO locations SET woj_id=24, name="Strumień";
INSERT INTO locations SET woj_id=24, name="Blachownia";
INSERT INTO locations SET woj_id=24, name="Koniecpol";
INSERT INTO locations SET woj_id=24, name="Sośnicowice";
INSERT INTO locations SET woj_id=24, name="Toszek";
INSERT INTO locations SET woj_id=24, name="Kłobuck";
INSERT INTO locations SET woj_id=24, name="Krzepice";
INSERT INTO locations SET woj_id=24, name="Woźniki";
INSERT INTO locations SET woj_id=24, name="Koziegłowy";
INSERT INTO locations SET woj_id=24, name="Żarki";
INSERT INTO locations SET woj_id=24, name="Pszczyna";
INSERT INTO locations SET woj_id=24, name="Krzanowice";
INSERT INTO locations SET woj_id=24, name="Kuźnia Raciborska";
INSERT INTO locations SET woj_id=24, name="Czerwionka-Leszczyny";
INSERT INTO locations SET woj_id=24, name="Łazy";
INSERT INTO locations SET woj_id=24, name="Ogrodzieniec";
INSERT INTO locations SET woj_id=24, name="Pilica";
INSERT INTO locations SET woj_id=24, name="Szczekociny";
INSERT INTO locations SET woj_id=24, name="Bielsko-Biała";
INSERT INTO locations SET woj_id=24, name="Bytom";
INSERT INTO locations SET woj_id=24, name="Chorzów";
INSERT INTO locations SET woj_id=24, name="Częstochowa";
INSERT INTO locations SET woj_id=24, name="Dąbrowa Górnicza";
INSERT INTO locations SET woj_id=24, name="Gliwice";
INSERT INTO locations SET woj_id=24, name="Jastrzębie-Zdrój";
INSERT INTO locations SET woj_id=24, name="Jaworzno";
INSERT INTO locations SET woj_id=24, name="Katowice";
INSERT INTO locations SET woj_id=24, name="Mysłowice";
INSERT INTO locations SET woj_id=24, name="Piekary Śląskie";
INSERT INTO locations SET woj_id=24, name="Ruda Śląska";
INSERT INTO locations SET woj_id=24, name="Rybnik";
INSERT INTO locations SET woj_id=24, name="Siemianowice Śląskie";
INSERT INTO locations SET woj_id=24, name="Sosnowiec";
INSERT INTO locations SET woj_id=24, name="Świętochłowice";
INSERT INTO locations SET woj_id=24, name="Tychy";
INSERT INTO locations SET woj_id=24, name="Zabrze";
INSERT INTO locations SET woj_id=24, name="Żory";
INSERT INTO locations SET woj_id=26, name="Busko-Zdrój";
INSERT INTO locations SET woj_id=26, name="Jędrzejów";
INSERT INTO locations SET woj_id=26, name="Małogoszcz";
INSERT INTO locations SET woj_id=26, name="Sędziszów";
INSERT INTO locations SET woj_id=26, name="Kazimierza Wielka";
INSERT INTO locations SET woj_id=26, name="Skalbmierz";
INSERT INTO locations SET woj_id=26, name="Bodzentyn";
INSERT INTO locations SET woj_id=26, name="Chęciny";
INSERT INTO locations SET woj_id=26, name="Chmielnik";
INSERT INTO locations SET woj_id=26, name="Daleszyce";
INSERT INTO locations SET woj_id=26, name="Końskie";
INSERT INTO locations SET woj_id=26, name="Stąporków";
INSERT INTO locations SET woj_id=26, name="Opatów";
INSERT INTO locations SET woj_id=26, name="Ożarów";
INSERT INTO locations SET woj_id=26, name="Ćmielów";
INSERT INTO locations SET woj_id=26, name="Kunów";
INSERT INTO locations SET woj_id=26, name="Działoszyce";
INSERT INTO locations SET woj_id=26, name="Pińczów";
INSERT INTO locations SET woj_id=26, name="Koprzywnica";
INSERT INTO locations SET woj_id=26, name="Zawichost";
INSERT INTO locations SET woj_id=26, name="Suchedniów";
INSERT INTO locations SET woj_id=26, name="Wąchock";
INSERT INTO locations SET woj_id=26, name="Osiek";
INSERT INTO locations SET woj_id=26, name="Połaniec";
INSERT INTO locations SET woj_id=26, name="Staszów";
INSERT INTO locations SET woj_id=26, name="Włoszczowa";
INSERT INTO locations SET woj_id=26, name="Kielce";
INSERT INTO locations SET woj_id=28, name="Bisztynek";
INSERT INTO locations SET woj_id=28, name="Sępopol";
INSERT INTO locations SET woj_id=28, name="Frombork";
INSERT INTO locations SET woj_id=28, name="Pieniężno";
INSERT INTO locations SET woj_id=28, name="Lidzbark";
INSERT INTO locations SET woj_id=28, name="Młynary";
INSERT INTO locations SET woj_id=28, name="Pasłęk";
INSERT INTO locations SET woj_id=28, name="Tolkmicko";
INSERT INTO locations SET woj_id=28, name="Ryn";
INSERT INTO locations SET woj_id=28, name="Kisielice";
INSERT INTO locations SET woj_id=28, name="Susz";
INSERT INTO locations SET woj_id=28, name="Zalewo";
INSERT INTO locations SET woj_id=28, name="Korsze";
INSERT INTO locations SET woj_id=28, name="Reszel";
INSERT INTO locations SET woj_id=28, name="Orneta";
INSERT INTO locations SET woj_id=28, name="Mikołajki";
INSERT INTO locations SET woj_id=28, name="Nidzica";
INSERT INTO locations SET woj_id=28, name="Olecko";
INSERT INTO locations SET woj_id=28, name="Barczewo";
INSERT INTO locations SET woj_id=28, name="Biskupiec";
INSERT INTO locations SET woj_id=28, name="Dobre Miasto";
INSERT INTO locations SET woj_id=28, name="Jeziorany";
INSERT INTO locations SET woj_id=28, name="Olsztynek";
INSERT INTO locations SET woj_id=28, name="Miłakowo";
INSERT INTO locations SET woj_id=28, name="Miłomłyn";
INSERT INTO locations SET woj_id=28, name="Morąg";
INSERT INTO locations SET woj_id=28, name="Biała Piska";
INSERT INTO locations SET woj_id=28, name="Orzysz";
INSERT INTO locations SET woj_id=28, name="Pisz";
INSERT INTO locations SET woj_id=28, name="Ruciane-Nida";
INSERT INTO locations SET woj_id=28, name="Pasym";
INSERT INTO locations SET woj_id=28, name="Gołdap";
INSERT INTO locations SET woj_id=28, name="Węgorzewo";
INSERT INTO locations SET woj_id=28, name="Elbląg";
INSERT INTO locations SET woj_id=28, name="Olsztyn";
INSERT INTO locations SET woj_id=30, name="Margonin";
INSERT INTO locations SET woj_id=30, name="Szamocin";
INSERT INTO locations SET woj_id=30, name="Krzyż Wielkopolski";
INSERT INTO locations SET woj_id=30, name="Trzcianka";
INSERT INTO locations SET woj_id=30, name="Wieleń";
INSERT INTO locations SET woj_id=30, name="Czerniejewo";
INSERT INTO locations SET woj_id=30, name="Kłecko";
INSERT INTO locations SET woj_id=30, name="Trzemeszno";
INSERT INTO locations SET woj_id=30, name="Witkowo";
INSERT INTO locations SET woj_id=30, name="Borek Wielkopolski";
INSERT INTO locations SET woj_id=30, name="Gostyń";
INSERT INTO locations SET woj_id=30, name="Krobia";
INSERT INTO locations SET woj_id=30, name="Pogorzela";
INSERT INTO locations SET woj_id=30, name="Poniec";
INSERT INTO locations SET woj_id=30, name="Grodzisk Wielkopolski";
INSERT INTO locations SET woj_id=30, name="Rakoniewice";
INSERT INTO locations SET woj_id=30, name="Wielichowo";
INSERT INTO locations SET woj_id=30, name="Jarocin";
INSERT INTO locations SET woj_id=30, name="Żerków";
INSERT INTO locations SET woj_id=30, name="Stawiszyn";
INSERT INTO locations SET woj_id=30, name="Kępno";
INSERT INTO locations SET woj_id=30, name="Dąbie";
INSERT INTO locations SET woj_id=30, name="Kłodawa";
INSERT INTO locations SET woj_id=30, name="Przedecz";
INSERT INTO locations SET woj_id=30, name="Golina";
INSERT INTO locations SET woj_id=30, name="Kleczew";
INSERT INTO locations SET woj_id=30, name="Rychwał";
INSERT INTO locations SET woj_id=30, name="Sompolno";
INSERT INTO locations SET woj_id=30, name="Ślesin";
INSERT INTO locations SET woj_id=30, name="Czempiń";
INSERT INTO locations SET woj_id=30, name="Krzywiń";
INSERT INTO locations SET woj_id=30, name="Śmigiel";
INSERT INTO locations SET woj_id=30, name="Kobylin";
INSERT INTO locations SET woj_id=30, name="Koźmin Wielkopolski";
INSERT INTO locations SET woj_id=30, name="Krotoszyn";
INSERT INTO locations SET woj_id=30, name="Zduny";
INSERT INTO locations SET woj_id=30, name="Osieczna";
INSERT INTO locations SET woj_id=30, name="Rydzyna";
INSERT INTO locations SET woj_id=30, name="Międzychód";
INSERT INTO locations SET woj_id=30, name="Sieraków";
INSERT INTO locations SET woj_id=30, name="Lwówek";
INSERT INTO locations SET woj_id=30, name="Nowy Tomyśl";
INSERT INTO locations SET woj_id=30, name="Opalenica";
INSERT INTO locations SET woj_id=30, name="Zbąszyń";
INSERT INTO locations SET woj_id=30, name="Oborniki";
INSERT INTO locations SET woj_id=30, name="Rogoźno";
INSERT INTO locations SET woj_id=30, name="Nowe Skalmierzyce";
INSERT INTO locations SET woj_id=30, name="Odolanów";
INSERT INTO locations SET woj_id=30, name="Raszków";
INSERT INTO locations SET woj_id=30, name="Grabów nad Prosną";
INSERT INTO locations SET woj_id=30, name="Mikstat";
INSERT INTO locations SET woj_id=30, name="Ostrzeszów";
INSERT INTO locations SET woj_id=30, name="Łobżenica";
INSERT INTO locations SET woj_id=30, name="Ujście";
INSERT INTO locations SET woj_id=30, name="Wyrzysk";
INSERT INTO locations SET woj_id=30, name="Wysoka";
INSERT INTO locations SET woj_id=30, name="Pleszew";
INSERT INTO locations SET woj_id=30, name="Buk";
INSERT INTO locations SET woj_id=30, name="Kostrzyn";
INSERT INTO locations SET woj_id=30, name="Kórnik";
INSERT INTO locations SET woj_id=30, name="Mosina";
INSERT INTO locations SET woj_id=30, name="Murowana Goślina";
INSERT INTO locations SET woj_id=30, name="Pobiedziska";
INSERT INTO locations SET woj_id=30, name="Stęszew";
INSERT INTO locations SET woj_id=30, name="Swarzędz";
INSERT INTO locations SET woj_id=30, name="Bojanowo";
INSERT INTO locations SET woj_id=30, name="Jutrosin";
INSERT INTO locations SET woj_id=30, name="Miejska Górka";
INSERT INTO locations SET woj_id=30, name="Rawicz";
INSERT INTO locations SET woj_id=30, name="Zagórów";
INSERT INTO locations SET woj_id=30, name="Ostroróg";
INSERT INTO locations SET woj_id=30, name="Pniewy";
INSERT INTO locations SET woj_id=30, name="Szamotuły";
INSERT INTO locations SET woj_id=30, name="Wronki";
INSERT INTO locations SET woj_id=30, name="Środa Wielkopolska";
INSERT INTO locations SET woj_id=30, name="Dolsk";
INSERT INTO locations SET woj_id=30, name="Książ Wielkopolski";
INSERT INTO locations SET woj_id=30, name="Śrem";
INSERT INTO locations SET woj_id=30, name="Dobra";
INSERT INTO locations SET woj_id=30, name="Tuliszków";
INSERT INTO locations SET woj_id=30, name="Gołańcz";
INSERT INTO locations SET woj_id=30, name="Skoki";
INSERT INTO locations SET woj_id=30, name="Wolsztyn";
INSERT INTO locations SET woj_id=30, name="Miłosław";
INSERT INTO locations SET woj_id=30, name="Nekla";
INSERT INTO locations SET woj_id=30, name="Pyzdry";
INSERT INTO locations SET woj_id=30, name="Września";
INSERT INTO locations SET woj_id=30, name="Jastrowie";
INSERT INTO locations SET woj_id=30, name="Krajenka";
INSERT INTO locations SET woj_id=30, name="Okonek";
INSERT INTO locations SET woj_id=30, name="Kalisz";
INSERT INTO locations SET woj_id=30, name="Konin";
INSERT INTO locations SET woj_id=30, name="Leszno";
INSERT INTO locations SET woj_id=30, name="Poznań";
