

INSERT INTO locations (id, woj_id, name) VALUES (12101, 12, 'Brzesko');
INSERT INTO locations (id, woj_id, name) VALUES (12102, 12, 'Czchów');
INSERT INTO locations (id, woj_id, name) VALUES (12103, 12, 'Alwernia');
INSERT INTO locations (id, woj_id, name) VALUES (12104, 12, 'Chrzanów');
INSERT INTO locations (id, woj_id, name) VALUES (12105, 12, 'Libiąż');
INSERT INTO locations (id, woj_id, name) VALUES (12106, 12, 'Trzebinia');
INSERT INTO locations (id, woj_id, name) VALUES (12107, 12, 'Dąbrowa Tarnowska');
INSERT INTO locations (id, woj_id, name) VALUES (12108, 12, 'Szczucin');
INSERT INTO locations (id, woj_id, name) VALUES (12109, 12, 'Biecz');
INSERT INTO locations (id, woj_id, name) VALUES (12110, 12, 'Bobowa');
INSERT INTO locations (id, woj_id, name) VALUES (12111, 12, 'Krzeszowice');
INSERT INTO locations (id, woj_id, name) VALUES (12112, 12, 'Skała');
INSERT INTO locations (id, woj_id, name) VALUES (12113, 12, 'Skawina');
INSERT INTO locations (id, woj_id, name) VALUES (12114, 12, 'Słomniki');
INSERT INTO locations (id, woj_id, name) VALUES (12115, 12, 'Świątniki Górne');
INSERT INTO locations (id, woj_id, name) VALUES (12116, 12, 'Miechów');
INSERT INTO locations (id, woj_id, name) VALUES (12117, 12, 'Dobczyce');
INSERT INTO locations (id, woj_id, name) VALUES (12118, 12, 'Myślenice');
INSERT INTO locations (id, woj_id, name) VALUES (12119, 12, 'Sułkowice');
INSERT INTO locations (id, woj_id, name) VALUES (12120, 12, 'Krynica-Zdrój');
INSERT INTO locations (id, woj_id, name) VALUES (12121, 12, 'Muszyna');
INSERT INTO locations (id, woj_id, name) VALUES (12122, 12, 'Piwniczna-Zdrój');
INSERT INTO locations (id, woj_id, name) VALUES (12123, 12, 'Stary Sącz');
INSERT INTO locations (id, woj_id, name) VALUES (12124, 12, 'Szczawnica');
INSERT INTO locations (id, woj_id, name) VALUES (12125, 12, 'Rabka-Zdrój');
INSERT INTO locations (id, woj_id, name) VALUES (12126, 12, 'Olkusz');
INSERT INTO locations (id, woj_id, name) VALUES (12127, 12, 'Wolbrom');
INSERT INTO locations (id, woj_id, name) VALUES (12128, 12, 'Brzeszcze');
INSERT INTO locations (id, woj_id, name) VALUES (12129, 12, 'Chełmek');
INSERT INTO locations (id, woj_id, name) VALUES (12130, 12, 'Kęty');
INSERT INTO locations (id, woj_id, name) VALUES (12131, 12, 'Zator');
INSERT INTO locations (id, woj_id, name) VALUES (12132, 12, 'Nowe Brzesko');
INSERT INTO locations (id, woj_id, name) VALUES (12133, 12, 'Proszowice');
INSERT INTO locations (id, woj_id, name) VALUES (12134, 12, 'Maków Podhalański');
INSERT INTO locations (id, woj_id, name) VALUES (12135, 12, 'Ciężkowice');
INSERT INTO locations (id, woj_id, name) VALUES (12136, 12, 'Radłów');
INSERT INTO locations (id, woj_id, name) VALUES (12137, 12, 'Ryglice');
INSERT INTO locations (id, woj_id, name) VALUES (12138, 12, 'Tuchów');
INSERT INTO locations (id, woj_id, name) VALUES (12139, 12, 'Wojnicz');
INSERT INTO locations (id, woj_id, name) VALUES (12140, 12, 'Zakliczyn');
INSERT INTO locations (id, woj_id, name) VALUES (12141, 12, 'Żabno');
INSERT INTO locations (id, woj_id, name) VALUES (12142, 12, 'Andrychów');
INSERT INTO locations (id, woj_id, name) VALUES (12143, 12, 'Kalwaria Zebrzydowska');
INSERT INTO locations (id, woj_id, name) VALUES (12144, 12, 'Wadowice');
INSERT INTO locations (id, woj_id, name) VALUES (12145, 12, 'Niepołomice');
INSERT INTO locations (id, woj_id, name) VALUES (12146, 12, 'Wieliczka');
INSERT INTO locations (id, woj_id, name) VALUES (12147, 12, 'Kraków');
INSERT INTO locations (id, woj_id, name) VALUES (12148, 12, 'Nowy Sącz');
INSERT INTO locations (id, woj_id, name) VALUES (12149, 12, 'Tarnów');
INSERT INTO locations (id, woj_id, name) VALUES (14100, 14, 'Białobrzegi');
INSERT INTO locations (id, woj_id, name) VALUES (14101, 14, 'Wyśmierzyce');
INSERT INTO locations (id, woj_id, name) VALUES (14102, 14, 'Glinojeck');
INSERT INTO locations (id, woj_id, name) VALUES (14103, 14, 'Pilawa');
INSERT INTO locations (id, woj_id, name) VALUES (14104, 14, 'Żelechów');
INSERT INTO locations (id, woj_id, name) VALUES (14105, 14, 'Grodzisk Mazowiecki');
INSERT INTO locations (id, woj_id, name) VALUES (14106, 14, 'Grójec');
INSERT INTO locations (id, woj_id, name) VALUES (14107, 14, 'Mogielnica');
INSERT INTO locations (id, woj_id, name) VALUES (14108, 14, 'Nowe Miasto nad Pilicą');
INSERT INTO locations (id, woj_id, name) VALUES (14109, 14, 'Warka');
INSERT INTO locations (id, woj_id, name) VALUES (14110, 14, 'Kozienice');
INSERT INTO locations (id, woj_id, name) VALUES (14111, 14, 'Serock');
INSERT INTO locations (id, woj_id, name) VALUES (14112, 14, 'Lipsko');
INSERT INTO locations (id, woj_id, name) VALUES (14113, 14, 'Łosice');
INSERT INTO locations (id, woj_id, name) VALUES (14114, 14, 'Różan');
INSERT INTO locations (id, woj_id, name) VALUES (14115, 14, 'Halinów');
INSERT INTO locations (id, woj_id, name) VALUES (14116, 14, 'Kałuszyn');
INSERT INTO locations (id, woj_id, name) VALUES (14117, 14, 'Nasielsk');
INSERT INTO locations (id, woj_id, name) VALUES (14118, 14, 'Zakroczym');
INSERT INTO locations (id, woj_id, name) VALUES (14119, 14, 'Myszyniec');
INSERT INTO locations (id, woj_id, name) VALUES (14120, 14, 'Brok');
INSERT INTO locations (id, woj_id, name) VALUES (14121, 14, 'Karczew');
INSERT INTO locations (id, woj_id, name) VALUES (14122, 14, 'Góra Kalwaria');
INSERT INTO locations (id, woj_id, name) VALUES (14123, 14, 'Konstancin-Jeziorna');
INSERT INTO locations (id, woj_id, name) VALUES (14124, 14, 'Piaseczno');
INSERT INTO locations (id, woj_id, name) VALUES (14125, 14, 'Tarczyn');
INSERT INTO locations (id, woj_id, name) VALUES (14126, 14, 'Drobin');
INSERT INTO locations (id, woj_id, name) VALUES (14127, 14, 'Gąbin');
INSERT INTO locations (id, woj_id, name) VALUES (14128, 14, 'Wyszogród');
INSERT INTO locations (id, woj_id, name) VALUES (14129, 14, 'Brwinów');
INSERT INTO locations (id, woj_id, name) VALUES (14130, 14, 'Chorzele');
INSERT INTO locations (id, woj_id, name) VALUES (14131, 14, 'Przysucha');
INSERT INTO locations (id, woj_id, name) VALUES (14132, 14, 'Pułtusk');
INSERT INTO locations (id, woj_id, name) VALUES (14133, 14, 'Iłża');
INSERT INTO locations (id, woj_id, name) VALUES (14134, 14, 'Skaryszew');
INSERT INTO locations (id, woj_id, name) VALUES (14135, 14, 'Mordy');
INSERT INTO locations (id, woj_id, name) VALUES (14136, 14, 'Kosów Lacki');
INSERT INTO locations (id, woj_id, name) VALUES (14137, 14, 'Szydłowiec');
INSERT INTO locations (id, woj_id, name) VALUES (14138, 14, 'Błonie');
INSERT INTO locations (id, woj_id, name) VALUES (14139, 14, 'Łomianki');
INSERT INTO locations (id, woj_id, name) VALUES (14140, 14, 'Ożarów Mazowiecki');
INSERT INTO locations (id, woj_id, name) VALUES (14141, 14, 'Łochów');
INSERT INTO locations (id, woj_id, name) VALUES (14142, 14, 'Radzymin');
INSERT INTO locations (id, woj_id, name) VALUES (14143, 14, 'Tłuszcz');
INSERT INTO locations (id, woj_id, name) VALUES (14144, 14, 'Wołomin');
INSERT INTO locations (id, woj_id, name) VALUES (14145, 14, 'Wyszków');
INSERT INTO locations (id, woj_id, name) VALUES (14146, 14, 'Zwoleń');
INSERT INTO locations (id, woj_id, name) VALUES (14147, 14, 'Bieżuń');
INSERT INTO locations (id, woj_id, name) VALUES (14148, 14, 'Żuromin');
INSERT INTO locations (id, woj_id, name) VALUES (14149, 14, 'Mszczonów');
INSERT INTO locations (id, woj_id, name) VALUES (14150, 14, 'Ostrołęka');
INSERT INTO locations (id, woj_id, name) VALUES (14151, 14, 'Płock');
INSERT INTO locations (id, woj_id, name) VALUES (14152, 14, 'Radom');
INSERT INTO locations (id, woj_id, name) VALUES (14153, 14, 'Siedlce');
INSERT INTO locations (id, woj_id, name) VALUES (14154, 14, 'Warszawa');
INSERT INTO locations (id, woj_id, name) VALUES (16100, 16, 'Grodków');
INSERT INTO locations (id, woj_id, name) VALUES (16101, 16, 'Lewin Brzeski');
INSERT INTO locations (id, woj_id, name) VALUES (16102, 16, 'Baborów');
INSERT INTO locations (id, woj_id, name) VALUES (16103, 16, 'Głubczyce');
INSERT INTO locations (id, woj_id, name) VALUES (16104, 16, 'Kietrz');
INSERT INTO locations (id, woj_id, name) VALUES (16105, 16, 'Byczyna');
INSERT INTO locations (id, woj_id, name) VALUES (16106, 16, 'Kluczbork');
INSERT INTO locations (id, woj_id, name) VALUES (16107, 16, 'Wołczyn');
INSERT INTO locations (id, woj_id, name) VALUES (16108, 16, 'Gogolin');
INSERT INTO locations (id, woj_id, name) VALUES (16109, 16, 'Krapkowice');
INSERT INTO locations (id, woj_id, name) VALUES (16110, 16, 'Zdzieszowice');
INSERT INTO locations (id, woj_id, name) VALUES (16111, 16, 'Namysłów');
INSERT INTO locations (id, woj_id, name) VALUES (16112, 16, 'Głuchołazy');
INSERT INTO locations (id, woj_id, name) VALUES (16113, 16, 'Korfantów');
INSERT INTO locations (id, woj_id, name) VALUES (16114, 16, 'Nysa');
INSERT INTO locations (id, woj_id, name) VALUES (16115, 16, 'Otmuchów');
INSERT INTO locations (id, woj_id, name) VALUES (16116, 16, 'Paczków');
INSERT INTO locations (id, woj_id, name) VALUES (16117, 16, 'Dobrodzień');
INSERT INTO locations (id, woj_id, name) VALUES (16118, 16, 'Gorzów Śląski');
INSERT INTO locations (id, woj_id, name) VALUES (16119, 16, 'Olesno');
INSERT INTO locations (id, woj_id, name) VALUES (16120, 16, 'Praszka');
INSERT INTO locations (id, woj_id, name) VALUES (16121, 16, 'Niemodlin');
INSERT INTO locations (id, woj_id, name) VALUES (16122, 16, 'Ozimek');
INSERT INTO locations (id, woj_id, name) VALUES (16123, 16, 'Prószków');
INSERT INTO locations (id, woj_id, name) VALUES (16124, 16, 'Biała');
INSERT INTO locations (id, woj_id, name) VALUES (16125, 16, 'Głogówek');
INSERT INTO locations (id, woj_id, name) VALUES (16126, 16, 'Prudnik');
INSERT INTO locations (id, woj_id, name) VALUES (16127, 16, 'Kolonowskie');
INSERT INTO locations (id, woj_id, name) VALUES (16128, 16, 'Leśnica');
INSERT INTO locations (id, woj_id, name) VALUES (16129, 16, 'Strzelce Opolskie');
INSERT INTO locations (id, woj_id, name) VALUES (16130, 16, 'Ujazd');
INSERT INTO locations (id, woj_id, name) VALUES (16131, 16, 'Zawadzkie');
INSERT INTO locations (id, woj_id, name) VALUES (16132, 16, 'Opole');
INSERT INTO locations (id, woj_id, name) VALUES (18100, 18, 'Ustrzyki Dolne');
INSERT INTO locations (id, woj_id, name) VALUES (18101, 18, 'Brzozów');
INSERT INTO locations (id, woj_id, name) VALUES (18102, 18, 'Brzostek');
INSERT INTO locations (id, woj_id, name) VALUES (18103, 18, 'Pilzno');
INSERT INTO locations (id, woj_id, name) VALUES (18104, 18, 'Pruchnik');
INSERT INTO locations (id, woj_id, name) VALUES (18105, 18, 'Kołaczyce');
INSERT INTO locations (id, woj_id, name) VALUES (18106, 18, 'Kolbuszowa');
INSERT INTO locations (id, woj_id, name) VALUES (18107, 18, 'Dukla');
INSERT INTO locations (id, woj_id, name) VALUES (18108, 18, 'Iwonicz-Zdrój');
INSERT INTO locations (id, woj_id, name) VALUES (18109, 18, 'Jedlicze');
INSERT INTO locations (id, woj_id, name) VALUES (18110, 18, 'Rymanów');
INSERT INTO locations (id, woj_id, name) VALUES (18111, 18, 'Nowa Sarzyna');
INSERT INTO locations (id, woj_id, name) VALUES (18112, 18, 'Cieszanów');
INSERT INTO locations (id, woj_id, name) VALUES (18113, 18, 'Narol');
INSERT INTO locations (id, woj_id, name) VALUES (18114, 18, 'Oleszyce');
INSERT INTO locations (id, woj_id, name) VALUES (18115, 18, 'Przecław');
INSERT INTO locations (id, woj_id, name) VALUES (18116, 18, 'Radomyśl Wielki');
INSERT INTO locations (id, woj_id, name) VALUES (18117, 18, 'Nisko');
INSERT INTO locations (id, woj_id, name) VALUES (18118, 18, 'Rudnik nad Sanem');
INSERT INTO locations (id, woj_id, name) VALUES (18119, 18, 'Ulanów');
INSERT INTO locations (id, woj_id, name) VALUES (18120, 18, 'Kańczuga');
INSERT INTO locations (id, woj_id, name) VALUES (18121, 18, 'Sieniawa');
INSERT INTO locations (id, woj_id, name) VALUES (18122, 18, 'Ropczyce');
INSERT INTO locations (id, woj_id, name) VALUES (18123, 18, 'Sędziszów Małopolski');
INSERT INTO locations (id, woj_id, name) VALUES (18124, 18, 'Błażowa');
INSERT INTO locations (id, woj_id, name) VALUES (18125, 18, 'Boguchwała');
INSERT INTO locations (id, woj_id, name) VALUES (18126, 18, 'Głogów Małopolski');
INSERT INTO locations (id, woj_id, name) VALUES (18127, 18, 'Sokołów Małopolski');
INSERT INTO locations (id, woj_id, name) VALUES (18128, 18, 'Tyczyn');
INSERT INTO locations (id, woj_id, name) VALUES (18129, 18, 'Zagórz');
INSERT INTO locations (id, woj_id, name) VALUES (18130, 18, 'Strzyżów');
INSERT INTO locations (id, woj_id, name) VALUES (18131, 18, 'Baranów Sandomierski');
INSERT INTO locations (id, woj_id, name) VALUES (18132, 18, 'Nowa Dęba');
INSERT INTO locations (id, woj_id, name) VALUES (18133, 18, 'Lesko');
INSERT INTO locations (id, woj_id, name) VALUES (18134, 18, 'Krosno');
INSERT INTO locations (id, woj_id, name) VALUES (18135, 18, 'Przemyśl');
INSERT INTO locations (id, woj_id, name) VALUES (18136, 18, 'Rzeszów');
INSERT INTO locations (id, woj_id, name) VALUES (18137, 18, 'Tarnobrzeg');
INSERT INTO locations (id, woj_id, name) VALUES (20100, 20, 'Lipsk');
INSERT INTO locations (id, woj_id, name) VALUES (20101, 20, 'Choroszcz');
INSERT INTO locations (id, woj_id, name) VALUES (20102, 20, 'Czarna Białostocka');
INSERT INTO locations (id, woj_id, name) VALUES (20103, 20, 'Łapy');
INSERT INTO locations (id, woj_id, name) VALUES (20104, 20, 'Michałowo');
INSERT INTO locations (id, woj_id, name) VALUES (20105, 20, 'Supraśl');
INSERT INTO locations (id, woj_id, name) VALUES (20106, 20, 'Suraż');
INSERT INTO locations (id, woj_id, name) VALUES (20107, 20, 'Tykocin');
INSERT INTO locations (id, woj_id, name) VALUES (20108, 20, 'Wasilków');
INSERT INTO locations (id, woj_id, name) VALUES (20109, 20, 'Zabłudów');
INSERT INTO locations (id, woj_id, name) VALUES (20110, 20, 'Rajgród');
INSERT INTO locations (id, woj_id, name) VALUES (20111, 20, 'Szczuczyn');
INSERT INTO locations (id, woj_id, name) VALUES (20112, 20, 'Kleszczele');
INSERT INTO locations (id, woj_id, name) VALUES (20113, 20, 'Stawiski');
INSERT INTO locations (id, woj_id, name) VALUES (20114, 20, 'Jedwabne');
INSERT INTO locations (id, woj_id, name) VALUES (20115, 20, 'Nowogród');
INSERT INTO locations (id, woj_id, name) VALUES (20116, 20, 'Goniądz');
INSERT INTO locations (id, woj_id, name) VALUES (20117, 20, 'Knyszyn');
INSERT INTO locations (id, woj_id, name) VALUES (20118, 20, 'Mońki');
INSERT INTO locations (id, woj_id, name) VALUES (20119, 20, 'Drohiczyn');
INSERT INTO locations (id, woj_id, name) VALUES (20120, 20, 'Dąbrowa Białostocka');
INSERT INTO locations (id, woj_id, name) VALUES (20121, 20, 'Krynki');
INSERT INTO locations (id, woj_id, name) VALUES (20122, 20, 'Sokółka');
INSERT INTO locations (id, woj_id, name) VALUES (20123, 20, 'Suchowola');
INSERT INTO locations (id, woj_id, name) VALUES (20124, 20, 'Ciechanowiec');
INSERT INTO locations (id, woj_id, name) VALUES (20125, 20, 'Czyżew');
INSERT INTO locations (id, woj_id, name) VALUES (20126, 20, 'Szepietowo');
INSERT INTO locations (id, woj_id, name) VALUES (20127, 20, 'Białystok');
INSERT INTO locations (id, woj_id, name) VALUES (20128, 20, 'Łomża');
INSERT INTO locations (id, woj_id, name) VALUES (20129, 20, 'Suwałki');
INSERT INTO locations (id, woj_id, name) VALUES (22100, 22, 'Bytów');
INSERT INTO locations (id, woj_id, name) VALUES (22101, 22, 'Miastko');
INSERT INTO locations (id, woj_id, name) VALUES (22102, 22, 'Brusy');
INSERT INTO locations (id, woj_id, name) VALUES (22103, 22, 'Czersk');
INSERT INTO locations (id, woj_id, name) VALUES (22104, 22, 'Czarne');
INSERT INTO locations (id, woj_id, name) VALUES (22105, 22, 'Debrzno');
INSERT INTO locations (id, woj_id, name) VALUES (22106, 22, 'Kartuzy');
INSERT INTO locations (id, woj_id, name) VALUES (22107, 22, 'Żukowo');
INSERT INTO locations (id, woj_id, name) VALUES (22108, 22, 'Prabuty');
INSERT INTO locations (id, woj_id, name) VALUES (22109, 22, 'Nowy Staw');
INSERT INTO locations (id, woj_id, name) VALUES (22110, 22, 'Nowy Dwór Gdański');
INSERT INTO locations (id, woj_id, name) VALUES (22111, 22, 'Kępice');
INSERT INTO locations (id, woj_id, name) VALUES (22112, 22, 'Skarszewy');
INSERT INTO locations (id, woj_id, name) VALUES (22113, 22, 'Gniew');
INSERT INTO locations (id, woj_id, name) VALUES (22114, 22, 'Pelplin');
INSERT INTO locations (id, woj_id, name) VALUES (22115, 22, 'Dzierzgoń');
INSERT INTO locations (id, woj_id, name) VALUES (22116, 22, 'Sztum');
INSERT INTO locations (id, woj_id, name) VALUES (22117, 22, 'Gdańsk');
INSERT INTO locations (id, woj_id, name) VALUES (22118, 22, 'Gdynia');
INSERT INTO locations (id, woj_id, name) VALUES (22119, 22, 'Słupsk');
INSERT INTO locations (id, woj_id, name) VALUES (22120, 22, 'Sopot');
INSERT INTO locations (id, woj_id, name) VALUES (24100, 24, 'Siewierz');
INSERT INTO locations (id, woj_id, name) VALUES (24101, 24, 'Czechowice-Dziedzice');
INSERT INTO locations (id, woj_id, name) VALUES (24102, 24, 'Wilamowice');
INSERT INTO locations (id, woj_id, name) VALUES (24103, 24, 'Skoczów');
INSERT INTO locations (id, woj_id, name) VALUES (24104, 24, 'Strumień');
INSERT INTO locations (id, woj_id, name) VALUES (24105, 24, 'Blachownia');
INSERT INTO locations (id, woj_id, name) VALUES (24106, 24, 'Koniecpol');
INSERT INTO locations (id, woj_id, name) VALUES (24107, 24, 'Sośnicowice');
INSERT INTO locations (id, woj_id, name) VALUES (24108, 24, 'Toszek');
INSERT INTO locations (id, woj_id, name) VALUES (24109, 24, 'Kłobuck');
INSERT INTO locations (id, woj_id, name) VALUES (24110, 24, 'Krzepice');
INSERT INTO locations (id, woj_id, name) VALUES (24111, 24, 'Woźniki');
INSERT INTO locations (id, woj_id, name) VALUES (24112, 24, 'Koziegłowy');
INSERT INTO locations (id, woj_id, name) VALUES (24113, 24, 'Żarki');
INSERT INTO locations (id, woj_id, name) VALUES (24114, 24, 'Pszczyna');
INSERT INTO locations (id, woj_id, name) VALUES (24115, 24, 'Krzanowice');
INSERT INTO locations (id, woj_id, name) VALUES (24116, 24, 'Kuźnia Raciborska');
INSERT INTO locations (id, woj_id, name) VALUES (24117, 24, 'Czerwionka-Leszczyny');
INSERT INTO locations (id, woj_id, name) VALUES (24118, 24, 'Łazy');
INSERT INTO locations (id, woj_id, name) VALUES (24119, 24, 'Ogrodzieniec');
INSERT INTO locations (id, woj_id, name) VALUES (24120, 24, 'Pilica');
INSERT INTO locations (id, woj_id, name) VALUES (24121, 24, 'Szczekociny');
INSERT INTO locations (id, woj_id, name) VALUES (24122, 24, 'Bielsko-Biała');
INSERT INTO locations (id, woj_id, name) VALUES (24123, 24, 'Bytom');
INSERT INTO locations (id, woj_id, name) VALUES (24124, 24, 'Chorzów');
INSERT INTO locations (id, woj_id, name) VALUES (24125, 24, 'Częstochowa');
INSERT INTO locations (id, woj_id, name) VALUES (24126, 24, 'Dąbrowa Górnicza');
INSERT INTO locations (id, woj_id, name) VALUES (24127, 24, 'Gliwice');
INSERT INTO locations (id, woj_id, name) VALUES (24128, 24, 'Jastrzębie-Zdrój');
INSERT INTO locations (id, woj_id, name) VALUES (24129, 24, 'Jaworzno');
INSERT INTO locations (id, woj_id, name) VALUES (24130, 24, 'Katowice');
INSERT INTO locations (id, woj_id, name) VALUES (24131, 24, 'Mysłowice');
INSERT INTO locations (id, woj_id, name) VALUES (24132, 24, 'Piekary Śląskie');
INSERT INTO locations (id, woj_id, name) VALUES (24133, 24, 'Ruda Śląska');
INSERT INTO locations (id, woj_id, name) VALUES (24134, 24, 'Rybnik');
INSERT INTO locations (id, woj_id, name) VALUES (24135, 24, 'Siemianowice Śląskie');
INSERT INTO locations (id, woj_id, name) VALUES (24136, 24, 'Sosnowiec');
INSERT INTO locations (id, woj_id, name) VALUES (24137, 24, 'Świętochłowice');
INSERT INTO locations (id, woj_id, name) VALUES (24138, 24, 'Tychy');
INSERT INTO locations (id, woj_id, name) VALUES (24139, 24, 'Zabrze');
INSERT INTO locations (id, woj_id, name) VALUES (24140, 24, 'Żory');
INSERT INTO locations (id, woj_id, name) VALUES (26100, 26, 'Busko-Zdrój');
INSERT INTO locations (id, woj_id, name) VALUES (26101, 26, 'Jędrzejów');
INSERT INTO locations (id, woj_id, name) VALUES (26102, 26, 'Małogoszcz');
INSERT INTO locations (id, woj_id, name) VALUES (26103, 26, 'Sędziszów');
INSERT INTO locations (id, woj_id, name) VALUES (26104, 26, 'Kazimierza Wielka');
INSERT INTO locations (id, woj_id, name) VALUES (26105, 26, 'Skalbmierz');
INSERT INTO locations (id, woj_id, name) VALUES (26106, 26, 'Bodzentyn');
INSERT INTO locations (id, woj_id, name) VALUES (26107, 26, 'Chęciny');
INSERT INTO locations (id, woj_id, name) VALUES (26108, 26, 'Chmielnik');
INSERT INTO locations (id, woj_id, name) VALUES (26109, 26, 'Daleszyce');
INSERT INTO locations (id, woj_id, name) VALUES (26110, 26, 'Końskie');
INSERT INTO locations (id, woj_id, name) VALUES (26111, 26, 'Stąporków');
INSERT INTO locations (id, woj_id, name) VALUES (26112, 26, 'Opatów');
INSERT INTO locations (id, woj_id, name) VALUES (26113, 26, 'Ożarów');
INSERT INTO locations (id, woj_id, name) VALUES (26114, 26, 'Ćmielów');
INSERT INTO locations (id, woj_id, name) VALUES (26115, 26, 'Kunów');
INSERT INTO locations (id, woj_id, name) VALUES (26116, 26, 'Działoszyce');
INSERT INTO locations (id, woj_id, name) VALUES (26117, 26, 'Pińczów');
INSERT INTO locations (id, woj_id, name) VALUES (26118, 26, 'Koprzywnica');
INSERT INTO locations (id, woj_id, name) VALUES (26119, 26, 'Zawichost');
INSERT INTO locations (id, woj_id, name) VALUES (26120, 26, 'Suchedniów');
INSERT INTO locations (id, woj_id, name) VALUES (26121, 26, 'Wąchock');
INSERT INTO locations (id, woj_id, name) VALUES (26122, 26, 'Osiek');
INSERT INTO locations (id, woj_id, name) VALUES (26123, 26, 'Połaniec');
INSERT INTO locations (id, woj_id, name) VALUES (26124, 26, 'Staszów');
INSERT INTO locations (id, woj_id, name) VALUES (26125, 26, 'Włoszczowa');
INSERT INTO locations (id, woj_id, name) VALUES (26126, 26, 'Kielce');
INSERT INTO locations (id, woj_id, name) VALUES (28100, 28, 'Bisztynek');
INSERT INTO locations (id, woj_id, name) VALUES (28101, 28, 'Sępopol');
INSERT INTO locations (id, woj_id, name) VALUES (28102, 28, 'Frombork');
INSERT INTO locations (id, woj_id, name) VALUES (28103, 28, 'Pieniężno');
INSERT INTO locations (id, woj_id, name) VALUES (28104, 28, 'Lidzbark');
INSERT INTO locations (id, woj_id, name) VALUES (28105, 28, 'Młynary');
INSERT INTO locations (id, woj_id, name) VALUES (28106, 28, 'Pasłęk');
INSERT INTO locations (id, woj_id, name) VALUES (28107, 28, 'Tolkmicko');
INSERT INTO locations (id, woj_id, name) VALUES (28108, 28, 'Ryn');
INSERT INTO locations (id, woj_id, name) VALUES (28109, 28, 'Kisielice');
INSERT INTO locations (id, woj_id, name) VALUES (28110, 28, 'Susz');
INSERT INTO locations (id, woj_id, name) VALUES (28111, 28, 'Zalewo');
INSERT INTO locations (id, woj_id, name) VALUES (28112, 28, 'Korsze');
INSERT INTO locations (id, woj_id, name) VALUES (28113, 28, 'Reszel');
INSERT INTO locations (id, woj_id, name) VALUES (28114, 28, 'Orneta');
INSERT INTO locations (id, woj_id, name) VALUES (28115, 28, 'Mikołajki');
INSERT INTO locations (id, woj_id, name) VALUES (28116, 28, 'Nidzica');
INSERT INTO locations (id, woj_id, name) VALUES (28117, 28, 'Olecko');
INSERT INTO locations (id, woj_id, name) VALUES (28118, 28, 'Barczewo');
INSERT INTO locations (id, woj_id, name) VALUES (28119, 28, 'Biskupiec');
INSERT INTO locations (id, woj_id, name) VALUES (28120, 28, 'Dobre Miasto');
INSERT INTO locations (id, woj_id, name) VALUES (28121, 28, 'Jeziorany');
INSERT INTO locations (id, woj_id, name) VALUES (28122, 28, 'Olsztynek');
INSERT INTO locations (id, woj_id, name) VALUES (28123, 28, 'Miłakowo');
INSERT INTO locations (id, woj_id, name) VALUES (28124, 28, 'Miłomłyn');
INSERT INTO locations (id, woj_id, name) VALUES (28125, 28, 'Morąg');
INSERT INTO locations (id, woj_id, name) VALUES (28126, 28, 'Biała Piska');
INSERT INTO locations (id, woj_id, name) VALUES (28127, 28, 'Orzysz');
INSERT INTO locations (id, woj_id, name) VALUES (28128, 28, 'Pisz');
INSERT INTO locations (id, woj_id, name) VALUES (28129, 28, 'Ruciane-Nida');
INSERT INTO locations (id, woj_id, name) VALUES (28130, 28, 'Pasym');
INSERT INTO locations (id, woj_id, name) VALUES (28131, 28, 'Gołdap');
INSERT INTO locations (id, woj_id, name) VALUES (28132, 28, 'Węgorzewo');
INSERT INTO locations (id, woj_id, name) VALUES (28133, 28, 'Elbląg');
INSERT INTO locations (id, woj_id, name) VALUES (28134, 28, 'Olsztyn');
INSERT INTO locations (id, woj_id, name) VALUES (30100, 30, 'Margonin');
INSERT INTO locations (id, woj_id, name) VALUES (30101, 30, 'Szamocin');
INSERT INTO locations (id, woj_id, name) VALUES (30102, 30, 'Krzyż Wielkopolski');
INSERT INTO locations (id, woj_id, name) VALUES (30103, 30, 'Trzcianka');
INSERT INTO locations (id, woj_id, name) VALUES (30104, 30, 'Wieleń');
INSERT INTO locations (id, woj_id, name) VALUES (30105, 30, 'Czerniejewo');
INSERT INTO locations (id, woj_id, name) VALUES (30106, 30, 'Kłecko');
INSERT INTO locations (id, woj_id, name) VALUES (30107, 30, 'Trzemeszno');
INSERT INTO locations (id, woj_id, name) VALUES (30108, 30, 'Witkowo');
INSERT INTO locations (id, woj_id, name) VALUES (30109, 30, 'Borek Wielkopolski');
INSERT INTO locations (id, woj_id, name) VALUES (30110, 30, 'Gostyń');
INSERT INTO locations (id, woj_id, name) VALUES (30111, 30, 'Krobia');
INSERT INTO locations (id, woj_id, name) VALUES (30112, 30, 'Pogorzela');
INSERT INTO locations (id, woj_id, name) VALUES (30113, 30, 'Poniec');
INSERT INTO locations (id, woj_id, name) VALUES (30114, 30, 'Grodzisk Wielkopolski');
INSERT INTO locations (id, woj_id, name) VALUES (30115, 30, 'Rakoniewice');
INSERT INTO locations (id, woj_id, name) VALUES (30116, 30, 'Wielichowo');
INSERT INTO locations (id, woj_id, name) VALUES (30117, 30, 'Jarocin');
INSERT INTO locations (id, woj_id, name) VALUES (30118, 30, 'Żerków');
INSERT INTO locations (id, woj_id, name) VALUES (30119, 30, 'Stawiszyn');
INSERT INTO locations (id, woj_id, name) VALUES (30120, 30, 'Kępno');
INSERT INTO locations (id, woj_id, name) VALUES (30121, 30, 'Dąbie');
INSERT INTO locations (id, woj_id, name) VALUES (30122, 30, 'Kłodawa');
INSERT INTO locations (id, woj_id, name) VALUES (30123, 30, 'Przedecz');
INSERT INTO locations (id, woj_id, name) VALUES (30124, 30, 'Golina');
INSERT INTO locations (id, woj_id, name) VALUES (30125, 30, 'Kleczew');
INSERT INTO locations (id, woj_id, name) VALUES (30126, 30, 'Rychwał');
INSERT INTO locations (id, woj_id, name) VALUES (30127, 30, 'Sompolno');
INSERT INTO locations (id, woj_id, name) VALUES (30128, 30, 'Ślesin');
INSERT INTO locations (id, woj_id, name) VALUES (30129, 30, 'Czempiń');
INSERT INTO locations (id, woj_id, name) VALUES (30130, 30, 'Krzywiń');
INSERT INTO locations (id, woj_id, name) VALUES (30131, 30, 'Śmigiel');
INSERT INTO locations (id, woj_id, name) VALUES (30132, 30, 'Kobylin');
INSERT INTO locations (id, woj_id, name) VALUES (30133, 30, 'Koźmin Wielkopolski');
INSERT INTO locations (id, woj_id, name) VALUES (30134, 30, 'Krotoszyn');
INSERT INTO locations (id, woj_id, name) VALUES (30135, 30, 'Zduny');
INSERT INTO locations (id, woj_id, name) VALUES (30136, 30, 'Osieczna');
INSERT INTO locations (id, woj_id, name) VALUES (30137, 30, 'Rydzyna');
INSERT INTO locations (id, woj_id, name) VALUES (30138, 30, 'Międzychód');
INSERT INTO locations (id, woj_id, name) VALUES (30139, 30, 'Sieraków');
INSERT INTO locations (id, woj_id, name) VALUES (30140, 30, 'Lwówek');
INSERT INTO locations (id, woj_id, name) VALUES (30141, 30, 'Nowy Tomyśl');
INSERT INTO locations (id, woj_id, name) VALUES (30142, 30, 'Opalenica');
INSERT INTO locations (id, woj_id, name) VALUES (30143, 30, 'Zbąszyń');
INSERT INTO locations (id, woj_id, name) VALUES (30144, 30, 'Oborniki');
INSERT INTO locations (id, woj_id, name) VALUES (30145, 30, 'Rogoźno');
INSERT INTO locations (id, woj_id, name) VALUES (30146, 30, 'Nowe Skalmierzyce');
INSERT INTO locations (id, woj_id, name) VALUES (30147, 30, 'Odolanów');
INSERT INTO locations (id, woj_id, name) VALUES (30148, 30, 'Raszków');
INSERT INTO locations (id, woj_id, name) VALUES (30149, 30, 'Grabów nad Prosną');
INSERT INTO locations (id, woj_id, name) VALUES (30150, 30, 'Mikstat');
INSERT INTO locations (id, woj_id, name) VALUES (30151, 30, 'Ostrzeszów');
INSERT INTO locations (id, woj_id, name) VALUES (30152, 30, 'Łobżenica');
INSERT INTO locations (id, woj_id, name) VALUES (30153, 30, 'Ujście');
INSERT INTO locations (id, woj_id, name) VALUES (30154, 30, 'Wyrzysk');
INSERT INTO locations (id, woj_id, name) VALUES (30155, 30, 'Wysoka');
INSERT INTO locations (id, woj_id, name) VALUES (30156, 30, 'Pleszew');
INSERT INTO locations (id, woj_id, name) VALUES (30157, 30, 'Buk');
INSERT INTO locations (id, woj_id, name) VALUES (30158, 30, 'Kostrzyn');
INSERT INTO locations (id, woj_id, name) VALUES (30159, 30, 'Kórnik');
INSERT INTO locations (id, woj_id, name) VALUES (30160, 30, 'Mosina');
INSERT INTO locations (id, woj_id, name) VALUES (30161, 30, 'Murowana Goślina');
INSERT INTO locations (id, woj_id, name) VALUES (30162, 30, 'Pobiedziska');
INSERT INTO locations (id, woj_id, name) VALUES (30163, 30, 'Stęszew');
INSERT INTO locations (id, woj_id, name) VALUES (30164, 30, 'Swarzędz');
INSERT INTO locations (id, woj_id, name) VALUES (30165, 30, 'Bojanowo');
INSERT INTO locations (id, woj_id, name) VALUES (30166, 30, 'Jutrosin');
INSERT INTO locations (id, woj_id, name) VALUES (30167, 30, 'Miejska Górka');
INSERT INTO locations (id, woj_id, name) VALUES (30168, 30, 'Rawicz');
INSERT INTO locations (id, woj_id, name) VALUES (30169, 30, 'Zagórów');
INSERT INTO locations (id, woj_id, name) VALUES (30170, 30, 'Ostroróg');
INSERT INTO locations (id, woj_id, name) VALUES (30171, 30, 'Pniewy');
INSERT INTO locations (id, woj_id, name) VALUES (30172, 30, 'Szamotuły');
INSERT INTO locations (id, woj_id, name) VALUES (30173, 30, 'Wronki');
INSERT INTO locations (id, woj_id, name) VALUES (30174, 30, 'Środa Wielkopolska');
INSERT INTO locations (id, woj_id, name) VALUES (30175, 30, 'Dolsk');
INSERT INTO locations (id, woj_id, name) VALUES (30176, 30, 'Książ Wielkopolski');
INSERT INTO locations (id, woj_id, name) VALUES (30177, 30, 'Śrem');
INSERT INTO locations (id, woj_id, name) VALUES (30178, 30, 'Dobra');
INSERT INTO locations (id, woj_id, name) VALUES (30179, 30, 'Tuliszków');
INSERT INTO locations (id, woj_id, name) VALUES (30180, 30, 'Gołańcz');
INSERT INTO locations (id, woj_id, name) VALUES (30181, 30, 'Skoki');
INSERT INTO locations (id, woj_id, name) VALUES (30182, 30, 'Wolsztyn');
INSERT INTO locations (id, woj_id, name) VALUES (30183, 30, 'Miłosław');
INSERT INTO locations (id, woj_id, name) VALUES (30184, 30, 'Nekla');
INSERT INTO locations (id, woj_id, name) VALUES (30185, 30, 'Pyzdry');
INSERT INTO locations (id, woj_id, name) VALUES (30186, 30, 'Września');
INSERT INTO locations (id, woj_id, name) VALUES (30187, 30, 'Jastrowie');
INSERT INTO locations (id, woj_id, name) VALUES (30188, 30, 'Krajenka');
INSERT INTO locations (id, woj_id, name) VALUES (30189, 30, 'Okonek');
INSERT INTO locations (id, woj_id, name) VALUES (30190, 30, 'Kalisz');
INSERT INTO locations (id, woj_id, name) VALUES (30191, 30, 'Konin');
INSERT INTO locations (id, woj_id, name) VALUES (30192, 30, 'Leszno');
INSERT INTO locations (id, woj_id, name) VALUES (30193, 30, 'Poznań');
